Sytem\Bundle\SGBundle\Entity\Dnsips:
    type: entity
    table: dnsips
    uniqueConstraints:
        ipdns:
            columns:
                - ipdns
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        ipdns:
            type: string
            nullable: false
            length: 15
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
