Sytem\Bundle\SGBundle\Entity\Laboratorios:
    type: entity
    table: laboratorios
    uniqueConstraints:
        nome_laboratorio:
            columns:
                - nome_laboratorio
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nomeLaboratorio:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
            column: nome_laboratorio
        bloco:
            type: string
            nullable: false
            length: 200
            fixed: false
            comment: ''
        sala:
            type: string
            nullable: false
            length: 60
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
