Sytem\Bundle\SGBundle\Entity\Tipos:
    type: entity
    table: tipos
    uniqueConstraints:
        descricao:
            columns:
                - descricao
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        descricao:
            type: string
            nullable: false
            length: 300
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
