Sytem\Bundle\SGBundle\Entity\Usuariosystem:
    type: entity
    table: usuariosystem
    uniqueConstraints:
        cpf_2:
            columns:
                - cpf
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nome:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
        telefone:
            type: string
            nullable: true
            length: 150
            fixed: false
            comment: ''
        email:
            type: string
            nullable: true
            length: 50
            fixed: false
            comment: ''
        cpf:
            type: string
            nullable: false
            length: 15
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
