tipos:
    path:     /
    defaults: { _controller: "SytemSGBundle:Tipos:index" }

tipos_show:
    path:     /{id}/show
    defaults: { _controller: "SytemSGBundle:Tipos:show" }

tipos_new:
    path:     /new
    defaults: { _controller: "SytemSGBundle:Tipos:new" }

tipos_create:
    path:     /create
    defaults: { _controller: "SytemSGBundle:Tipos:create" }
    requirements: { _method: post }

tipos_edit:
    path:     /{id}/edit
    defaults: { _controller: "SytemSGBundle:Tipos:edit" }

tipos_update:
    path:     /{id}/update
    defaults: { _controller: "SytemSGBundle:Tipos:update" }
    requirements: { _method: post|put }

tipos_delete:
    path:     /{id}/delete
    defaults: { _controller: "SytemSGBundle:Tipos:delete" }
    requirements: { _method: post|delete }
