security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Sytem\Bundle\SGBundle\Entity\UserLDAP:
            id: custom_md5_encoder

    role_hierarchy:
        ROLE_ADMIN:       
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        userLDAP:
            id: user_ldap_provider
        # in_memory:
        #     memory:
        #         users:
        #             user:  { password: userpass, roles: [ 'ROLE_USER' ] }
        #             admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/
            anonymous: ~

            form_login:
                login_path:  /
                check_path:  /login_check
                #default_target_path: /admin/homeadmin
                always_use_default_target_path: true
                use_referer: false
                provider: userLDAP
                #provider: 
                #userLDAP            
            logout:
                path:   /logout
                invalidate_session: false

            #http_basic:
                #realm: "Secured Demo Area"
                #provider: 
    access_control:
        #- { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        - { path: ^/admin/, roles: ROLE_ADMIN }
        - { path: ^/user/, roles: ROLE_USER }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }