Solicitacoes:
    type: entity
    table: solicitacoes
    indexes:
        laboratorio_id:
            columns:
                - laboratorio_id
        responsavel:
            columns:
                - responsavel
        usuario:
            columns:
                - usuario
        tipo:
            columns:
                - tipo
    id:
        id:
            type: bigint
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dataSolicitacao:
            type: date
            nullable: false
            comment: ''
            column: data_solicitacao
        avaliacao:
            type: string
            nullable: true
            length: 30
            fixed: false
            comment: ''
            default: 'no valued'
        motivo:
            type: string
            nullable: true
            length: 400
            fixed: false
            comment: ''
        respaval:
            type: string
            nullable: true
            length: 40
            fixed: false
            comment: ''
        justificativa:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        descricaoequip:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
        mac:
            type: string
            nullable: false
            length: 17
            fixed: false
            comment: ''
        file:
            type: string
            nullable: true
            length: 600
            fixed: false
            comment: ''
    manyToOne:
        laboratorio:
            targetEntity: Laboratorios
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                laboratorio_id:
                    referencedColumnName: id
            orphanRemoval: false
        responsavel:
            targetEntity: Usuariosystem
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                responsavel:
                    referencedColumnName: id
            orphanRemoval: false
        usuario:
            targetEntity: Usuariosystem
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                usuario:
                    referencedColumnName: id
            orphanRemoval: false
        tipo:
            targetEntity: Tipos
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                tipo:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
